import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {newDiagram,newObject,clone,duplicateObjects,deleteObjects,moveObjects,rotateObjects,saveVariant,restoreVariant,createHistory,previewPosition,diagramErrors,calibrate} from '../src/shot-workspace/model.js';
import {drawDiagram,pathLegs,offsetLine,hitObjects,imagePoint} from '../src/shot-workspace/renderer.js';
import {csvCell,shotCsv} from '../src/shot-workspace/exports.js';
import {captureMapView} from '../src/shot-workspace/capture.js';
import {createWorkspaceRepo} from '../src/data/workspace-repo.js';
import {createFakeIndexedDB} from './fixtures/indexeddb.mjs';
import {projectFixture,FIXTURE_IDS} from './fixtures/project.mjs';
import {copyWithNewIds} from '../src/data/conflicts.js';
import {buildEnvelope,parseEnvelope,serializeEnvelope} from '../src/data/transfer.js';
import {newId} from '../src/domain/ids.js';
const region=JSON.parse(readFileSync(new URL('../data/region/lafayette.region.json',import.meta.url),'utf8'));
function scene(){const d=newDiagram(),o=newObject('camera',100,100);o.path=[{x:100,y:100},{x:300,y:100},{x:450,y:250}];d.objects.push(o);return d;}
function context(){const calls=[],stack=[];const target={calls,save(){stack.push({fillStyle:this.fillStyle,strokeStyle:this.strokeStyle});},restore(){Object.assign(this,stack.pop());},measureText:s=>({width:s.length*8}),getImageData:()=>({data:new Uint8ClampedArray([50,60,70,255])})};return new Proxy(target,{get(t,k){return k in t?t[k]:(...args)=>calls.push({name:k,args,color:t.fillStyle,stroke:t.strokeStyle});}});}
test('path steps repeat symbols, number every step, use neutral camera lines without mutating records',()=>{const d=scene(),before=clone(d),ctx=context();drawDiagram(ctx,d,null);assert.deepEqual(d,before);assert.equal(ctx.calls.filter(c=>c.name==='fillRect'&&c.args[0]===-19.5).length,3);assert.deepEqual(ctx.calls.filter(c=>c.name==='fillText'&&/^\d+$/.test(c.args[0])).map(c=>c.args[0]),['1','2','3']);assert.ok(ctx.calls.filter(c=>c.name==='stroke'&&c.stroke==='#18252e').length>=4);assert.equal(hitObjects(d,{x:450,y:250})[0].id,d.objects[0].id);});
test('curved path legs meet every authored point and reverse deterministically',()=>{const o=scene().objects[0];o.curved=true;const legs=pathLegs(o);assert.deepEqual(legs[0][0],o.path[0]);assert.deepEqual(legs[0].at(-1),o.path[1]);assert.deepEqual(legs.at(-1).at(-1),o.path.at(-1));const mid=previewPosition(o,1.2);o.path.reverse();const reverse=previewPosition(o,o.duration-1.2);assert.ok(Math.hypot(mid.x-reverse.x,mid.y-reverse.y)<1e-8);assert.deepEqual(offsetLine([{x:0,y:0},{x:100,y:0}],10),[{x:0,y:10},{x:100,y:10}]);});
test('actor paths use actor symbols for all steps; hidden objects are excluded',()=>{const d=scene();d.objects[0].type='actor';const ctx=context();drawDiagram(ctx,d,null);assert.equal(ctx.calls.filter(c=>c.name==='arc'&&c.args[2]===16.5).length,3);d.objects[0].hidden=true;const hidden=context();drawDiagram(hidden,d,null);assert.equal(hidden.calls.filter(c=>c.name==='arc').length,0);});
test('independent camera setups, locked transforms and undo restore complete arrangements',()=>{const d=scene(),o=d.objects[0],id=duplicateObjects(d,[o.id],true)[0],setup=d.objects.find(o=>o.id===id);assert.equal(setup.rigId,o.rigId);assert.notEqual(setup.setup,o.setup);o.locked=true;moveObjects(d,[o.id,id],20,10);assert.equal(o.x,100);assert.equal(setup.x,145);deleteObjects(d,[o.id]);assert.ok(d.objects.includes(o));const h=createHistory(d);const next=clone(d);rotateObjects(next,[id],90);h.commit(next);h.undo();assert.deepEqual(h.value,d);h.redo();assert.deepEqual(h.value,next);});
test('variants preserve background, paths and optics and do not recursively nest',()=>{const d=scene();saveVariant(d,'Original');const saved=clone(d);d.objects[0].lens.focalLengthMm=85;d.objects[0].path.reverse();const restored=restoreVariant(d,d.variants[0].id);assert.deepEqual(restored,saved);assert.equal('variants' in restored.variants[0].snapshot,false);});
test('calibration refuses oblique images and validates independent check',()=>{const d=newDiagram();d.background.kind='owned';d.background.oblique=true;assert.throws(()=>calibrate(d,{x:0,y:0},{x:100,y:0},10,{x:0,y:0},{x:50,y:0},5));d.background.oblique=false;calibrate(d,{x:0,y:0},{x:100,y:0},10,{x:0,y:0},{x:50,y:0},5);assert.equal(d.calibration.errorPct,0);assert.equal(d.calibration.metresPerPixel,.1);});
test('malformed imported identities and camera references are rejected',()=>{const d=scene();d.objects.push(clone(d.objects[0]));assert.ok(diagramErrors(d).length);const e=scene();e.objects[0].path[0].x=NaN;assert.ok(diagramErrors(e).length);});
test('CSV preserves Unicode, quotes and zero while neutralizing formulas',()=>{assert.equal(csvCell(' =SUM(A1)'), '"\' =SUM(A1)"');assert.equal(csvCell('a"b'), '"a""b"');const d=scene();d.shots.push({id:newId('shot'),cameraId:d.objects[0].id,number:'1',shotType:'wide',description:'Café',movement:'',duration:0,status:'planned',notes:'=cmd'});const csv=shotCsv({diagram:d,name:'Scene',revision:1});assert.ok(csv.includes('Café'));assert.ok(csv.includes('"0"'));assert.ok(csv.includes('"\'=cmd"'));assert.deepEqual(imagePoint({x:30,y:40},{x:10,y:20,scale:2}),{x:10,y:10});});
test('diagram roundtrip and copy preserve bytes and remap object/shot identities',async()=>{const bundle=projectFixture();bundle.shotScenes[0].diagram=scene();const d=bundle.shotScenes[0].diagram;d.shots.push({id:newId('shot'),cameraId:d.objects[0].id,number:'1',shotType:'',description:'',movement:'',duration:5,status:'planned',notes:''});saveVariant(d,'A');const repo=createWorkspaceRepo({factory:createFakeIndexedDB().factory,storage:region.storage});await repo.open();await repo.writeProjectBundle(bundle);assert.deepEqual((await repo.getShotScene(FIXTURE_IDS.shotScene)).diagram,d);const parsed=parseEnvelope(serializeEnvelope(buildEnvelope({bundle,catalogVersion:'1.1.0',exportedAt:'2026-09-26T12:00:00Z'})));assert.equal(parsed.ok,true);const copied=copyWithNewIds(bundle).bundle.shotScenes[0].diagram;assert.notEqual(copied.objects[0].id,d.objects[0].id);assert.equal(copied.shots[0].cameraId,copied.objects[0].id);assert.equal(copied.variants[0].snapshot.objects[0].id,copied.objects[0].id);});
function captureFixture(){const events=new Map(),ctx=context();let zoom=12;const map={getCenter:()=>({lng:-92,lat:30}),getZoom:()=>zoom,getBearing:()=>0,getPitch:()=>0,getCanvas:()=>({width:400,height:200}),on:(e,f)=>events.set(e,f),off:e=>events.delete(e),triggerRepaint(){},isMoving:()=>false,areTilesLoaded:()=>true};const doc={createElement:()=>({getContext:()=>ctx,toDataURL:()=> 'data:image/png;base64,AAAA'})};return {map,doc,ctx,events,change(){zoom++;}};}
test('capture uses current credits at render time and removes listeners',async()=>{const f=captureFixture();let credit='old';const pending=captureMapView({...f,source:'test',attribution:()=>credit});credit='new credit';f.events.get('render')();const bg=await pending;assert.equal(bg.attribution,credit);assert.ok(f.ctx.calls.some(c=>c.name==='fillText'&&c.args[0]===credit));assert.equal(f.events.size,0);});
test('capture rejects a changed view without leaving listeners',async()=>{const f=captureFixture();const pending=captureMapView({...f,source:'test',attribution:'credit'});f.change();f.events.get('render')();await assert.rejects(pending,/changed/);assert.equal(f.events.size,0);});
test('capture timeout retains bounded lifecycle',async()=>{const f=captureFixture();await assert.rejects(captureMapView({...f,source:'test',attribution:'credit',isReady:()=>false,timeoutMs:5}),/ready/);assert.equal(f.events.size,0);});

test('spaced curves bow automatically while preserving steps and deterministic preview',()=>{const o=scene().objects[0];o.pathStyle='spaced';const before=clone(o);const legs=pathLegs(o);assert.deepEqual(legs[0][0],o.path[0]);assert.deepEqual(legs[0].at(-1),o.path[1]);assert.ok(legs[0][12].y>100);assert.deepEqual(o,before);assert.deepEqual(previewPosition(o,0),o.path[0]);assert.deepEqual(previewPosition(o,o.duration),o.path.at(-1));o.pathStyle='straight';assert.equal(pathLegs(o)[0].length,2);});
test('path step numbers are drawn inside icons without circular badges',()=>{const d=scene(),ctx=context();drawDiagram(ctx,d,null);assert.equal(ctx.calls.filter(c=>c.name==='arc').length,0);const numbers=ctx.calls.filter(c=>c.name==='fillText'&&/^\d+$/.test(c.args[0]));assert.equal(numbers.length,3);numbers.forEach((c,i)=>{assert.ok(Math.abs(c.args[1]-d.objects[0].path[i].x)<30);assert.equal(c.args[2],d.objects[0].path[i].y);});});
