import { QUESTIONS, SECTIONS } from "../scouting/assessment-template.js";
import { ENTRY_LIMITATION } from "../immersive/bookmarks.js";

export const PACKET_SECTIONS = ["decisions", "dossiers", "assessments", "evidence", "bookmarks", "diagrams", "shots"];
export const escapeHtml = value => String(value ?? "").replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]);
const valueText = value => typeof value === "object" && value !== null ? JSON.stringify(value, null, 2) : String(value ?? "Information has not been found");
const table = (headers, rows) => `<table><thead><tr>${headers.map(h => `<th scope="col">${escapeHtml(h)}</th>`).join("")}</tr></thead><tbody>${rows.map(row => `<tr>${row.map(cell => `<td><pre>${escapeHtml(valueText(cell))}</pre></td>`).join("")}</tr>`).join("")}</tbody></table>`;
const image = url => typeof url === "string" && /^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/]+=*$/.test(url) ? `<img alt="Shot diagram with attribution and calibration notes" src="${url}">` : "<p>Diagram image unavailable; records remain in the project backup.</p>";

/** Build a self-contained packet; all authored text is escaped, with no remote resources. */
export function packetHtml({ envelope, sections = PACKET_SECTIONS, assessmentIds = null, assessmentSections = null, mediaIds = null, catalog = null, diagrams = {}, css = "" }) {
  const b = envelope.payload, p = b.projects[0], selected = new Set(sections), parts = [];
  const assessments = b.scoutAssessments.filter(a => !assessmentIds || assessmentIds.includes(a.id));
  const section = (id, title, content) => { if (selected.has(id)) parts.push(`<section><h2>${escapeHtml(title)}</h2>${content}</section>`); };
  const answerRows = answers => answers.filter(a => !assessmentSections || assessmentSections.some(id => sectionQuestions[id]?.has(a.questionId))).map(a => [QUESTIONS.find(q => q.id === a.questionId)?.label ?? a.questionId, a.state,
    a.numberValue ?? a.booleanValue ?? a.textValue ?? "Information has not been found", [a.note, a.referenceUrl].filter(Boolean).join("\n"), a.bookmarkId ?? "", a.mediaIds ?? []]);
  section("decisions", "Scene requirements and candidate decisions", b.scenes.map(s => `<h3>${escapeHtml(s.number)} — ${escapeHtml(s.title)}</h3>${table(["Scene ID / revision", "Requirements", "Decision and remaining questions"], [[`${s.id} / ${s.revision}`, { mustHave:s.mustHave, preferred:s.preferred, rejectionConditions:s.rejectionConditions }, { decisions:s.decisions, openQuestions:s.openQuestions }]])}`).join("")
    + table(["Candidate / location / scene", "Status and rationale", "Concerns / missing information", "Requirement evidence"], b.candidates.map(c => [`${c.id}\n${c.locationId}\n${c.sceneId}`, { status:c.status, rationale:c.rationale, notes:c.decisionNotes }, { concerns:c.concerns, missingInfo:c.missingInfo }, c.evaluations ?? c.requirementAssessments])));
  const locations = [...new Set(b.candidates.map(c => c.locationId))];
  section("dossiers", "Public dossier summaries", `<p>Current catalog ${escapeHtml(catalog?.version ?? "unavailable")}; project catalog ${escapeHtml(envelope.catalogVersion)}. Public hours are not production availability. Operator, property owner and filming authority are distinct. A capture is not filming permission.</p>`
    + locations.map(id => `<h3>${escapeHtml(catalog?.locations?.find(l => l.id === id)?.name ?? id)}</h3>${table(["Public field", "Recorded value"], [...Object.entries(catalog?.locations?.find(l => l.id === id) ?? {locationId:id}), ...Object.entries(catalog?.scoutDetails?.find?.(l => l.locationId === id) ?? {details:"Information has not been found"})])}`).join(""));
  section("assessments", "Selected scouting assessments", assessments.map(a => `<h3>${escapeHtml(a.title)} — revision ${a.revision}</h3><p>${escapeHtml(a.id)} | ${escapeHtml(a.locationId)} | ${escapeHtml(a.sourceKind)} | ${escapeHtml(a.observedAt ?? a.observationDate ?? a.updatedAt)}</p><p>${escapeHtml(a.sourceNote)}</p>${table(["Question", "State", "Recorded value", "Notes", "Bookmark", "Media IDs"], answerRows(a.answers))}`).join(""));
  const candidateVersions = [...b.candidates, ...b.scenes.flatMap(s => (s.decisions ?? []).flatMap(d => d.candidateSnapshots ?? []))];
  const referenced = new Set(candidateVersions.flatMap(c => (c.evaluations ?? []).map(e => e.assessmentRevisionId)));
  for (const scene of b.shotScenes) for (const ref of [...(scene.diagram?.evidence ?? []), ...(scene.diagram?.variants ?? []).flatMap(v => v.snapshot.evidence ?? [])]) {
    const revision = b.scoutAssessmentRevisions.find(r => r.assessmentId === ref.assessmentId && r.revision === ref.revision);
    if (revision) referenced.add(revision.id);
  }
  const revisions = b.scoutAssessmentRevisions.filter(r => referenced.has(r.id));
  const media = b.scoutMedia.filter(m => !mediaIds || mediaIds.includes(m.id));
  section("evidence", "Evidence revisions and media", `<p>Observed means recorded from the named source, not independently verified. Candidate links identify immutable revision IDs; later edits do not replace that evidence.</p>`
    + revisions.map(r => `<h3>${escapeHtml(r.id)}</h3><p>${escapeHtml(r.assessmentId)} / revision ${escapeHtml(r.snapshot.revision)}</p>${table(["Question", "State", "Recorded value", "Notes", "Bookmark", "Media IDs"], answerRows(r.snapshot.answers))}`).join("")
    + table(["Media ID / file", "Source", "Availability"], media.map(m => [`${m.id}\n${m.filename}`, m.provenance, m.missing ? "Missing — recover from original source" : "Included in project backup"]))
    + media.map(m => { const asset=envelope.assetsInline.find(a => a.assetId===m.id); return asset && /^image\/(png|jpeg|webp)$/.test(m.mime) ? `<figure>${image(`data:${m.mime};base64,${asset.data}`)}<figcaption>${escapeHtml(m.filename)} — ${escapeHtml(m.provenance)}</figcaption></figure>` : ""; }).join(""));
  section("bookmarks", "Entry bookmarks", `<p>${escapeHtml(ENTRY_LIMITATION)}</p>` + table(["Bookmark ID", "Location / capture", "Note"], b.bookmarks.map(b => [b.id, `${b.locationId} / ${b.captureId}`, b.note ?? b.notes]))
    + b.bookmarks.map(b => `<p><a href="https://sroberto27.github.io/SLiVR/#/immersive/${encodeURIComponent(b.locationId)}">${escapeHtml(b.name ?? b.id)} — ${escapeHtml(b.locationId)} catalog entry</a></p>`).join(""));
  section("diagrams", "Shot diagrams", b.shotScenes.map(s => `<h3>${escapeHtml(s.name)} — revision ${s.revision}</h3><p>${escapeHtml(s.id)} | Scene ${escapeHtml(s.sceneId)} | Location ${escapeHtml(s.locationId)}</p>${s.diagram ? image(diagrams[s.id]) : "<p>Legacy ENU design retained in JSON; no image-overlay conversion inferred.</p>"}<p>${escapeHtml(s.diagram?.background.attribution)} ${escapeHtml(s.diagram?.background.source)}</p><p>Image overlays and paths are schematic. Scale applies only to a calibrated owned flat plan, never an oblique screenshot.</p>`).join(""));
  section("shots", "Shot lists", b.shotScenes.map(s => `<h3>${escapeHtml(s.name)}</h3>${table(["Shot / ID", "Camera / setup", "Lens / gate / aspect", "Movement / duration", "Description / notes / status"], s.diagram ? s.diagram.shots.map(shot => { const camera=s.diagram.objects.find(o=>o.id===shot.cameraId); return [`${shot.number} / ${shot.id}`, `${camera?.label} / ${camera?.setup}`, camera?.lens, `${shot.movement} / ${shot.duration} seconds`, `${shot.description}\n${shot.notes}\n${shot.status}`]; }) : b.shots.filter(shot=>shot.shotSceneId===s.id).map(shot=>[shot.id,shot.cameraObjectId,"Legacy ENU — see JSON",shot.movement,shot.description]))}`).join(""));
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data:; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>${escapeHtml(p.name)} — SLiVR scouting packet</title><style>${css.replaceAll("</", "<\\/")}</style></head><body><header><h1>${escapeHtml(p.name)}</h1><p>SLiVR scouting packet | ${escapeHtml(envelope.exportedAt)} | project revision ${p.revision}</p><p>${escapeHtml(p.id)} | App ${escapeHtml(envelope.appVersion)} / transfer ${escapeHtml(envelope.schemaVersion)} / catalog ${escapeHtml(envelope.catalogVersion)}</p><p class="screen-only">Use your browser’s Print command to save as PDF.</p><p class="note">Remote screening and schematic shot planning. Need validation remains unresolved; this packet is not filming authorization or a completed technical scout.</p></header>${parts.join("")}</body></html>`;
}

const sectionQuestions = Object.fromEntries(SECTIONS.map(s => [s.id, new Set(s.questions.map(q => q.id))]));
